name: test-ci

on:
  workflow_dispatch:
    inputs:
      start-e2e:
        required: true
        type: choice
        description: defines if the workflow shoule be started or not
        options: 
          - run
          - skip
jobs:
  e2e:
    runs-on: ubuntu-latest
    container:
      image: node:20.8.1
    steps:
      - uses: actions/checkout@v4.1.0
      - name: E2E
        run: echo "E2E"
  
