name: issue

# on:
#   workflow_dispatch:
#     inputs:
#       start-pipeline:
#         required: true
#         type: choice
#         description: defines if the workflow shoule be started or not
#         options: 
#           - run 

on:
  pull_request:
    types: [opened, synchronize]
    branches:
      - main

permissions:
  contents: read
  issues: write 

jobs:
  manual-approve-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: create an issue
        uses: dacbd/create-issue-action@main
        with:
          token: ${{ github.token }}
          title: Deploy ${{ github.event.pull_request.commits_url }} to Production
          body: Number of commits ${{ github.event.pull_request.commits }}
          labels: deploy