name: issue

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pull-requests: write

jobs:
  create-pr:
    runs-on: ubuntu-latest
    environment: general
    steps:
      - uses: actions/checkout@v3
      - name: Open PR Merge
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITKEY }}
          title: Merge to branch via evans
          branch: staing
          base: main

