name: issue

# on:
#   workflow_dispatch:
#     inputs:
#       start-pipeline:
#         required: true
#         type: choice
#         description: defines if the workflow shoule be started or not
#         options: 
#           - run

on:
  push:
    branches:
      - main

jobs:
  manual-approve-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Create github issue
        run: cat ./../../issue_template.md | github-issue create