name: issue

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pull-requests: write

jobs:
  create-pr:
    runs-on: ubuntu-latest
    environment: general
    steps:
      - name: Run the Action
        uses: devops-infra/action-pull-request@v0.5.5
        with:
          github_token: ${{ secrets.GITKEY }}
          source_branch: main
          target_branch: staging
          title: My pull request