name: Sync multiple branches

on:
    workflow_call:
        inputs: 
            source:
                required: true
                type: string
            target:
                required: true
                type: string

jobs:
  sync-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Merge development -> staging
        uses: devmasx/merge-branch@master
        with:
          type: now
          from_branch: ${{ inputs.source }}
          target_branch: ${{ inputs.target }}
          github_token: ${{ secrets.GITHUB_TOKEN }}