name: test-ci

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    # container:
    #   image: node:20.8.1
    steps:
      # - uses: actions/checkout@v4.1.0
      - name: Define current base
        run: echo "TEST"