name: test-ci
on: push
jobs:
  build-and-test:
    if: ${{ inputs.run_workflow_build }}
    runs-on: ubuntu-latest
    container:
      image: node:20.8.1
    steps:
    - uses: actions/checkout@v4.1.0
    - name: Define current base
      run: |-
        BASE=main~1
        if [ "${{ github.ref }}" = "staging" ]; then
          BASE=staging~1
        elif [ "${{ github.ref }}" = "production" ]; then
          BASE=production~1
        fi
        echo "export BASE=$BASE" >> $BASH_ENV
        echo $BASE
  sonarscan:
    if: ${{ inputs.run_workflow_build }}
    runs-on: ubuntu-latest
    container:
      image: node:20.8.1
    needs:
    - build-and-test
    steps:
    - uses: actions/checkout@v4.1.0
    - uses: actions/download-artifact@v3.0.2
      with:
        path: "."