name: test-ci

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    # container:
    #   image: node:20.8.1
    steps:
      # - uses: actions/checkout@v4.1.0
      - name: Build
        run: echo "BUILD"
  test:
    runs-on: ubuntu-latest
    # container:
    #   image: node:20.8.1
    steps:
      # - uses: actions/checkout@v4.1.0
      - name: Test
        run: echo "TEST"
    needs:
      - build
  sonar:
    runs-on: ubuntu-latest
    steps:
      - name: Sonar check
        run: echo "SONAR"
    needs:
      - test
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/workflows/reusable-deploy.yml
        with: 
          env: "design"
    needs: 
      - sonar