name: test-ci

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: node:20.8.1
    steps:
      - uses: actions/checkout@v4.1.0
      - name: Build
        run: echo "BUILD"
  test:
    runs-on: ubuntu-latest
    container:
      image: node:20.8.1
    steps:
      - uses: actions/checkout@v4.1.0
      - name: Test
        run: echo "TEST"
  sonar:
    runs-on: ubuntu-latest
    steps:
      - name: Sonar check
        run: echo "SONAR"
  deploy:
    # maybe check for deploy flag here
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to design
        run: echo "SONAR"
        
  # starts e2e workflow at the end of spinnaker deploy
  
