name: production

on:
  workflow_dispatch:
    inputs:
      start-pipeline:
        required: true
        type: choice
        description: defines if the workflow shoule be started or not
        options: 
          - run

jobs:
  # maybe open here an issue - if that issue is resolved trigger deploy pipeline
  manual-approve-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Approve
        run: echo "Manual approve or create issue (or maybe this is done in spinnaker)"
  # so everything after here is done in another workflow
  push-to-ecr:
    uses: ./.github/workflows/reusable_ecr_push.yml
    with:
      region: eu-west-1
  deploy:
    uses: ./.github/workflows/reusable_deploy.yml
    with: 
      env: "production"
    secrets: inherit
    needs: 
      - manual-approve-deploy

