name: test-ci

on:
  workflow_dispatch:
    inputs:
      start-pipeline:
        required: true
        type: choice
        description: defines if the workflow shoule be started or not
        options: 
          - run

jobs:
  manual-approve-deploy:
    name: manual-approve-deploy
    runs-on: ubuntu-latest
    steps:
      - uses: trstringer/manual-approval@v1
        with: 
          approvers: skrubi9
  deploy:
    uses: ./.github/workflows/reusable-deploy.yml
    with: 
      env: "production"
    secrets: inherit
    needs: 
      - manual-approve-deploy

