name: production

on:
  workflow_dispatch:
    inputs:
      start-pipeline:
        required: true
        type: choice
        description: defines if the workflow shoule be started or not
        options: 
          - run

jobs:
  manual-approve-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Approve
        run: echo "Manual approve or create issue (or maybe this is done in spinnaker)"
  deploy:
    uses: ./.github/workflows/reusable-deploy.yml
    with: 
      env: "production"
    secrets: inherit
    needs: 
      - manual-approve-deploy

