name: production

on:
  issues:
    types: [closed]

jobs:
  deploy:
    if: ${{ github.event.label.name == 'deploy' }}
    uses: ./.github/workflows/reusable_deploy.yml
    with: 
      env: "production"
    secrets: inherit