name: production

on:
  issues:
    types: [closed]

jobs:
  deploy:
    if: contains(github.event.issue.labels.*.name, 'deploy')
    uses: ./.github/workflows/reusable_deploy.yml
    with: 
      env: "production"
    secrets: inherit