name: reusable-deploy

on:
    workflow_call:
        inputs: 
            env:
                required: true
                type: string

jobs:
  print-env:
    runs-on: ubuntu-latest
    steps:
      - name: Printer
        run: echo "Env is ${{ inputs.env }}"

  auto-call-design:
    environment: general
    runs-on: ubuntu-latest
    if: ${{inputs.env == 'design' }}
    steps:
        - name: call-design-test-step
          run: |
            curl -L -X POST -H "Accept: application/vnd.github+json" -H "Authorization: Bearer ${{ secrets.GITKEY }}" -H "X-GitHub-Api-Version: 2022-11-28" https://api.github.com/repos/skrubi9/gitactions/actions/workflows/design-test/dispatches -d '{"ref":"main","inputs":{"start-pipeline":"run"}}'
    needs: 
        - print-env

  auto-call-production:
    environment: general 
    runs-on: ubuntu-latest
    if: ${{inputs.env == 'staging' }}
    steps:
        - name: call-production-deploy-step
          run: |
            curl -L -X POST -H "Accept: application/vnd.github+json" -H "Authorization: Bearer ${{ secrets.GITKEY }}" -H "X-GitHub-Api-Version: 2022-11-28" https://api.github.com/repos/skrubi9/gitactions/actions/workflows/production/dispatches -d '{"ref":"main","inputs":{"start-pipeline":"run"}}'
    needs: 
      - print-env

  do-production-deploy:
    runs-on: ubuntu-latest
    if: ${{inputs.env == 'production' }}
    steps:
        - name: do-prod-deploy
          run: echo "DO PROD DEPLOY"
    needs:
        - print-env