name: reusable-deploy

on:
    workflow_call:
        inputs: 
            env:
                required: true
                type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to ${{ inputs.env }}
        run: echo "Deploy to ${{ inputs.env }}"

  auto-call-design: 
    runs-on: ubuntu-latest
    if: ${{inputs.env}} == "design"
    steps:
        - name: call-design-test-step
          run: |
            curl -L -X POST -H "Accept: application/vnd.github+json" -H "Authorization: Bearer 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" -H "X-GitHub-Api-Version: 2022-11-28" https://api.github.com/repos/skrubi9/gitactions/actions/workflows/design-test/dispatches -d '{"ref":"main","inputs":{"start-pipeline":"run"}}'
    needs: 
        - deploy

  auto-call-production: 
    runs-on: ubuntu-latest
    if: ${{inputs.env}} == "staging"
    steps:
        - name: call-production-deploy-step
          run: |
            curl -L -X POST -H "Accept: application/vnd.github+json" -H "Authorization: Bearer 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" -H "X-GitHub-Api-Version: 2022-11-28" https://api.github.com/repos/skrubi9/gitactions/actions/workflows/production/dispatches -d '{"ref":"main","inputs":{"start-pipeline":"run"}}'
    needs: 
      - deploy

  do-production-deploy:
    runs-on: ubuntu-latest
    if: ${{inputs.env}} == "production"
    steps:
        - name: do-prod-deploy
          run: echo "DO PROD DEPLOY"