name: Reusable AWS S3 Deployment Workflow

on:
    workflow_call:
        inputs:
            environment:
                description: 'Environment to be deployed to'
                required: true
                type: string
            artifact_name:
                description: 'Name of artifact to be fetched'
                required: true
                type: string
        outputs:
            artifact-built:
                description: "Defines if a new artifact was built and deployed to artifactory"
                value: ${{ jobs.publish.outputs.artifact-built }}

# permissions:
#     id-token: write

jobs:
    print:
        runs-on: ubuntu-latest
        outputs:
            artifact-built: ${{ steps.check.outputs.exists }}
        steps:
            - name: Printer
              run: echo "exists=false" >> "$GITHUB_OUTPUT"
              
    # deploy:
    #     name: Deploy to S3
    #     runs-on: ubuntu-latest
    #     environment: ${{ inputs.environment }}
    #     steps:
    #     - name: Fetch artifact
    #         uses: actions/download-artifact@v3
    #         with:
    #         name: ${{ inputs.artifact_name }}
    #         path: dist

    #     - name: Configure AWS Credentials
    #         uses: aws-actions/configure-aws-credentials@v3
    #         with:
    #         role-to-assume: ${{ vars.AWS_S3_BUCKET_ACCESS_ROLE }}
    #         aws-region: ${{ vars.AWS_REGION }}

    #     - name: Sync files with S3
    #         run: |
    #         echo "Uploading to S3..."
    #         aws s3 sync --delete ./dist ${{ vars.AWS_S3_BUCKET_PATH }}