name: artifactory push

on:
    workflow_call:
        inputs: 
            artifact_name:
                required: true
                type: string
            artifact_name_2:
                required: true
                type: string

jobs:
    print:
        if: (inputs.artifact_name == 'true' && inputs.artifact_name_2 == 'true')
        runs-on: ubuntu-latest
        steps:
            - name: Printer
              run: echo "Env is ${{ inputs.artifact_name }}"

    # toArtifactory:
    #     uses: actions/upload-artifact@v3
    #     with:
    #         name: ${{ inputs.artifact_name }}
    #         path: ${{ inputs.artifact_directory }}
    #         retention-days: 1