name: design test

on:
  workflow_dispatch:
    inputs:
      start-pipeline:
        required: true
        type: choice
        description: defines if the workflow shoule be started or not
        options: 
          - run

jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
      - name: E2E
        run: echo "E2E"
  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - name: Lighthouse
        run: echo "LIGHTHOUSE"
  deploy:
    uses: ./.github/workflows/reusable-deploy.yml
    with: 
      env: "staging"
    secrets: inherit
    needs: 
      - e2e
      - lighthouse