name: pipeline

on:
  push:
    branches:
      - main

jobs:
  print:
    runs-on: ubuntu-latest
    steps:
      - name: print
        run: echo "${{ github.event.pull_request.base.sha }}"

  build:
    runs-on: ubuntu-latest
    container:
      image: node:20.8.1
    steps:
      - uses: actions/checkout@v4.1.0
        with:
          fetch-depth: 0
      - name: Use Node.js 20
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: npm
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: "./node_modules/.bin/nx affected --target=build --parallel=false --base=remotes/origin/main --head=HEAD --prod"

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Test
        run: echo "TEST"
    needs:
      - build

  sonar:
    runs-on: ubuntu-latest
    steps:
      - name: Sonar check
        run: echo "SONAR"
    needs:
      - test

  push-to-ecr-backend:
    uses: ./.github/workflows/reusable_ecr_push.yml
    with:
      aws_region: eu-west-1
      assume_role: assume role
      ecr_repo: backend
    needs: 
      - sonar

  push-to-ecr-backend-cms:
    uses: ./.github/workflows/reusable_ecr_push.yml
    with:
      aws_region: eu-west-1
      assume_role: assume role
      ecr_repo: cms-backend
    needs: 
      - sonar

  push-to-s3-frontend:
    uses: ./.github/workflows/reusable_s3_push.yml
    with:
      environment: frontend
      artifact_name: nameOfArtifact
    needs: 
      - sonar

  push-to-s3-frontend-cms:
    uses: ./.github/workflows/reusable_s3_push.yml
    with:
      environment: cms-frontend
      artifact_name: nameOfArtifact
    needs: 
      - sonar

  # deploy:
  #   uses: ./.github/workflows/reusable_deploy.yml
  #   with: 
  #     env: "design"
  #   secrets: inherit
  #   needs: 
  #     - push-to-ecr-backend
  #     - push-to-ecr-backend-cms
  #     - push-to-s3-frontend
  #     - push-to-s3-frontend-cms