name: pipeline

on:
  push:
    branches:
      - main

jobs: 
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.0
        with:
          fetch-depth: 0
      - name: print branch
        run: |
          echo "ref ${{ github.ref }}"
          echo "head_ref ${{ github.head_ref }}"
          echo "base_ref ${{ github.base_ref }}"
          echo "ref.head ${{ github.ref.HEAD }} "
