name: pipeline

on:
  repository_dispatch:
    types: 
      - run-post-spinnaker

jobs: 
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.0
        with:
          fetch-depth: 0
      - name: print branch
        run: |
          echo ref ${{ github.ref }}
          echo head_ref ${{ github.head_ref }}
          echo base_ref ${{ github.base_ref }}
  
  if-test: 
    if: (${{ github.base_ref }} === 'main')
    runs-on: ubuntu-latest
    name: Deploy to 
    steps:
      - run: echo "=== main"

  if-test-2: 
    if: (${{ github.base_ref }} !== 'main')
    runs-on: ubuntu-latest
    name: Deploy to 
    steps:
      - run: echo "!== main" 