name: pipeline

on:
  push:
    branches:
      - main
      - staging

jobs: 
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.0
        with:
          fetch-depth: 0
      - name: print branch
        run: |
          echo "base_ref ${{ github.ref_name }} " 
