name: pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    # container:
    #   image: node:20.8.1
    steps:
      # - uses: actions/checkout@v4.1.0
      - name: Build
        run: echo "BUILD"
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Test
        run: echo "TEST"
    needs:
      - build
  sonar:
    runs-on: ubuntu-latest
    steps:
      - name: Sonar check
        run: echo "SONAR"
    needs:
      - test
  push-to-ecr:
    uses: ./.github/workflows/reusable_ecr_push.yml
    with:
      region: eu-west-1
  deploy:
    uses: ./.github/workflows/reusable_deploy.yml
    with: 
      env: "design"
    secrets: inherit
    needs: 
      - sonar