name: pr pipeline

on:
  pull_request:
    types: [opened, synchronize]
    branches:
      - main   

jobs:
  # build-and-test:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4.1.0
  #       with:
  #         fetch-depth: 0
  #     - name: Create .npmrc
  #       run: cp .npmrc.template .npmrc
  #     - name: Use Node.js 20
  #       uses: actions/setup-node@v3
  #       with:
  #         node-version: 20
  #         cache: npm
  #     - name: Install dependencies
  #       run: npm ci
  #     - uses: nrwl/nx-set-shas@v3
  #     - run: git config --global --add safe.directory /__w/gitactions/gitactions
  #     - name: Create a dummy .env file to be able to run the tests
  #       run: touch .env
  #     - name: Build
  #       run: ./node_modules/.bin/nx affected --target=build --parallel=false --prod
  #     - name: Store the version
  #       run: |-
  #         export BUILD_VERSION=$(git rev-parse --abbrev-ref HEAD)-$(git rev-parse --short HEAD)
  #         echo "$BUILD_VERSION-${{github.run_number}}" > VERSION
  #         echo "Stored version " `cat VERSION`
  #     - uses: actions/upload-artifact@v3
  #       with:
  #         name: buildfiles
  #         path: |-
  #           ./dist/*
  #           ./VERSION
  #           ./.npmrc
  lighthouse:
    runs-on: self-hosted
    permissions:
        contents: read
        id-token: write
    steps:
      - uses: actions/checkout@v4.1.0
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 20
      - uses: browser-actions/setup-chrome@v1
      - uses: browser-tools/install-chromedriver
      - name: Run lhci
        run: |
          npm install -g @lhci/cli@0.12.x
          lhci autorun